/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
)

// PhotosAPIService PhotosAPI service
type PhotosAPIService service

type ApiCreatePhotoRequest struct {
	ctx           context.Context
	ApiService    *PhotosAPIService
	file          *os.File
	caption       *string
	companyId     *int32
	photoableType *string
	photoableId   *int32
	folderId      *int32
	pinned        *bool
}

// The image file to upload
func (r ApiCreatePhotoRequest) File(file *os.File) ApiCreatePhotoRequest {
	r.file = file
	return r
}

// Caption/title for the photo
func (r ApiCreatePhotoRequest) Caption(caption string) ApiCreatePhotoRequest {
	r.caption = &caption
	return r
}

// ID of the company this photo belongs to
func (r ApiCreatePhotoRequest) CompanyId(companyId int32) ApiCreatePhotoRequest {
	r.companyId = &companyId
	return r
}

// Type of record to attach the photo to (Company, Asset, Article, etc.)
func (r ApiCreatePhotoRequest) PhotoableType(photoableType string) ApiCreatePhotoRequest {
	r.photoableType = &photoableType
	return r
}

// ID of the record to attach the photo to
func (r ApiCreatePhotoRequest) PhotoableId(photoableId int32) ApiCreatePhotoRequest {
	r.photoableId = &photoableId
	return r
}

// ID of the folder to place the photo in
func (r ApiCreatePhotoRequest) FolderId(folderId int32) ApiCreatePhotoRequest {
	r.folderId = &folderId
	return r
}

// Whether the photo should be pinned
func (r ApiCreatePhotoRequest) Pinned(pinned bool) ApiCreatePhotoRequest {
	r.pinned = &pinned
	return r
}

func (r ApiCreatePhotoRequest) Execute() (*CreatePhoto201Response, *http.Response, error) {
	return r.ApiService.CreatePhotoExecute(r)
}

/*
CreatePhoto Create a new Photo

Uploads and creates a new photo. The photo can be attached to a photoable record (Company, Asset, Article, etc.) or created standalone.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreatePhotoRequest
*/
func (a *PhotosAPIService) CreatePhoto(ctx context.Context) ApiCreatePhotoRequest {
	return ApiCreatePhotoRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CreatePhoto201Response
func (a *PhotosAPIService) CreatePhotoExecute(r ApiCreatePhotoRequest) (*CreatePhoto201Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CreatePhoto201Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PhotosAPIService.CreatePhoto")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/photos"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.file == nil {
		return localVarReturnValue, nil, reportError("file is required and must be specified")
	}
	if r.caption == nil {
		return localVarReturnValue, nil, reportError("caption is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var fileLocalVarFormFileName string
	var fileLocalVarFileName string
	var fileLocalVarFileBytes []byte

	fileLocalVarFormFileName = "file"
	fileLocalVarFile := r.file

	if fileLocalVarFile != nil {
		fbs, _ := io.ReadAll(fileLocalVarFile)

		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	}
	parameterAddToHeaderOrQuery(localVarFormParams, "caption", r.caption, "", "")
	if r.companyId != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "company_id", r.companyId, "", "")
	}
	if r.photoableType != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "photoable_type", r.photoableType, "", "")
	}
	if r.photoableId != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "photoable_id", r.photoableId, "", "")
	}
	if r.folderId != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "folder_id", r.folderId, "", "")
	}
	if r.pinned != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "pinned", r.pinned, "", "")
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v CreatePhoto422Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeletePhotoRequest struct {
	ctx        context.Context
	ApiService *PhotosAPIService
	id         int32
}

func (r ApiDeletePhotoRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeletePhotoExecute(r)
}

/*
DeletePhoto Delete a Photo

Permanently deletes a photo. This action is irreversible and requires an API key with destructive action permissions.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id ID of the Photo to delete
	@return ApiDeletePhotoRequest
*/
func (a *PhotosAPIService) DeletePhoto(ctx context.Context, id int32) ApiDeletePhotoRequest {
	return ApiDeletePhotoRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
func (a *PhotosAPIService) DeletePhotoExecute(r ApiDeletePhotoRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PhotosAPIService.DeletePhoto")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/photos/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v CreatePhoto422Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetPhotoRequest struct {
	ctx        context.Context
	ApiService *PhotosAPIService
	id         int32
	download   *bool
}

// If true, downloads the photo file instead of returning JSON metadata
func (r ApiGetPhotoRequest) Download(download bool) ApiGetPhotoRequest {
	r.download = &download
	return r
}

func (r ApiGetPhotoRequest) Execute() (*CreatePhoto201Response, *http.Response, error) {
	return r.ApiService.GetPhotoExecute(r)
}

/*
GetPhoto Get a specific Photo

Returns a single photo by ID, including its archive status. Optionally download the photo file by setting download=true.

**CORS Configuration for Browser Testing**: If you experience CORS errors or "Failed to fetch" when testing the download endpoint in browser-based tools (e.g., Swagger UI), you need to configure CORS on your cloud storage bucket (DigitalOcean Spaces/S3) with: (1) Origin: `https://your-domain.com`, (2) Allowed Methods: `GET`, `HEAD`, (3) Allowed Headers: `*`

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id ID of the Photo to retrieve
	@return ApiGetPhotoRequest
*/
func (a *PhotosAPIService) GetPhoto(ctx context.Context, id int32) ApiGetPhotoRequest {
	return ApiGetPhotoRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CreatePhoto201Response
func (a *PhotosAPIService) GetPhotoExecute(r ApiGetPhotoRequest) (*CreatePhoto201Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CreatePhoto201Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PhotosAPIService.GetPhoto")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/photos/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.download != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "download", r.download, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetPhotosRequest struct {
	ctx           context.Context
	ApiService    *PhotosAPIService
	companyId     *int32
	photoableType *string
	photoableId   *int32
	folderId      *int32
	archived      *bool
	createdAt     *string
	updatedAt     *string
	page          *int32
	pageSize      *int32
}

// Filter by company ID
func (r ApiGetPhotosRequest) CompanyId(companyId int32) ApiGetPhotosRequest {
	r.companyId = &companyId
	return r
}

// Filter by photoable type (Company, Asset, Article, etc.)
func (r ApiGetPhotosRequest) PhotoableType(photoableType string) ApiGetPhotosRequest {
	r.photoableType = &photoableType
	return r
}

// Filter by photoable record ID
func (r ApiGetPhotosRequest) PhotoableId(photoableId int32) ApiGetPhotosRequest {
	r.photoableId = &photoableId
	return r
}

// Filter by folder ID
func (r ApiGetPhotosRequest) FolderId(folderId int32) ApiGetPhotosRequest {
	r.folderId = &folderId
	return r
}

// Filter by archived status. true &#x3D; only archived, false &#x3D; only non-archived. If omitted, defaults to non-archived only.
func (r ApiGetPhotosRequest) Archived(archived bool) ApiGetPhotosRequest {
	r.archived = &archived
	return r
}

// Filter by creation date (YYYY-MM-DD or start,end for range)
func (r ApiGetPhotosRequest) CreatedAt(createdAt string) ApiGetPhotosRequest {
	r.createdAt = &createdAt
	return r
}

// Filter by update date (YYYY-MM-DD or start,end for range)
func (r ApiGetPhotosRequest) UpdatedAt(updatedAt string) ApiGetPhotosRequest {
	r.updatedAt = &updatedAt
	return r
}

// Page number for pagination
func (r ApiGetPhotosRequest) Page(page int32) ApiGetPhotosRequest {
	r.page = &page
	return r
}

// Number of results per page (1-1000, default: 25)
func (r ApiGetPhotosRequest) PageSize(pageSize int32) ApiGetPhotosRequest {
	r.pageSize = &pageSize
	return r
}

func (r ApiGetPhotosRequest) Execute() (*GetPhotos200Response, *http.Response, error) {
	return r.ApiService.GetPhotosExecute(r)
}

/*
GetPhotos Get a list of Photos

Returns a list of photos. By default, returns only non-archived photos. Use the archived parameter to filter by archive status.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetPhotosRequest
*/
func (a *PhotosAPIService) GetPhotos(ctx context.Context) ApiGetPhotosRequest {
	return ApiGetPhotosRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return GetPhotos200Response
func (a *PhotosAPIService) GetPhotosExecute(r ApiGetPhotosRequest) (*GetPhotos200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GetPhotos200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PhotosAPIService.GetPhotos")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/photos"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.companyId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "company_id", r.companyId, "", "")
	}
	if r.photoableType != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "photoable_type", r.photoableType, "", "")
	}
	if r.photoableId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "photoable_id", r.photoableId, "", "")
	}
	if r.folderId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "folder_id", r.folderId, "", "")
	}
	if r.archived != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "archived", r.archived, "", "")
	}
	if r.createdAt != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "created_at", r.createdAt, "", "")
	}
	if r.updatedAt != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "updated_at", r.updatedAt, "", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "", "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdatePhotoRequest struct {
	ctx        context.Context
	ApiService *PhotosAPIService
	id         int32
	photo      *UpdatePhotoRequest
}

// Photo attributes. Must be wrapped in a &#x60;photo&#x60; key. Include only the attributes you want to update. Example: {\&quot;photo\&quot;: {\&quot;caption\&quot;: \&quot;New caption\&quot;, \&quot;pinned\&quot;: true}}
func (r ApiUpdatePhotoRequest) Photo(photo UpdatePhotoRequest) ApiUpdatePhotoRequest {
	r.photo = &photo
	return r
}

func (r ApiUpdatePhotoRequest) Execute() (*CreatePhoto201Response, *http.Response, error) {
	return r.ApiService.UpdatePhotoExecute(r)
}

/*
UpdatePhoto Update a Photo

Updates a photo's metadata. The request body must be wrapped in a `photo` key. Editable attributes: caption, folder_id, pinned, archived, photoable_type, photoable_id. Note: company_id is derived from photoable and cannot be set directly—change photoable_type and photoable_id to update the company. To archive/unarchive, set the archived field to true/false.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id ID of the Photo to update
	@return ApiUpdatePhotoRequest
*/
func (a *PhotosAPIService) UpdatePhoto(ctx context.Context, id int32) ApiUpdatePhotoRequest {
	return ApiUpdatePhotoRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CreatePhoto201Response
func (a *PhotosAPIService) UpdatePhotoExecute(r ApiUpdatePhotoRequest) (*CreatePhoto201Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CreatePhoto201Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PhotosAPIService.UpdatePhoto")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/photos/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.photo == nil {
		return localVarReturnValue, nil, reportError("photo is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.photo
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["APIKeyHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v CreatePhoto422Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
