/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the UpdateProcedureTaskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProcedureTaskRequest{}

// UpdateProcedureTaskRequest struct for UpdateProcedureTaskRequest
type UpdateProcedureTaskRequest struct {
	// The name of the task. **Process tasks only** - cannot be changed on run tasks.
	Name *string `json:"name,omitempty"`
	// A detailed description of the task. **Process tasks only** - cannot be changed on run tasks.
	Description *string `json:"description,omitempty"`
	// The ID of the process or run this task belongs to. **Process tasks only** - can be changed to move tasks between processes. Cannot be changed on run tasks.
	ProcedureId *int32 `json:"procedure_id,omitempty"`
	// The position of the task in the process. **Process tasks only** - cannot be changed on run tasks.
	Position *int32 `json:"position,omitempty"`
	// The due date for the task. **Run tasks only** - rejected on process tasks.
	DueDate *string `json:"due_date,omitempty"`
	// The priority level of the task. **Run tasks only** - rejected on process tasks.
	Priority *string `json:"priority,omitempty"`
	// An array of user IDs assigned to the task. **Run tasks only** - rejected on process tasks.
	AssignedUsers []int32 `json:"assigned_users,omitempty"`
	// Whether the task is optional. Optional tasks don't need to be completed for the process/run to be considered complete. **Process tasks only** - cannot be changed on run tasks.
	Optional *bool `json:"optional,omitempty"`
	// The ID of the parent task if this is a subtask. Set to null to make it a top-level task. Subtasks cannot have their own subtasks (no nested subtasks). **Process tasks only** - cannot be changed on run tasks.
	ParentTaskId         *int32 `json:"parent_task_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateProcedureTaskRequest UpdateProcedureTaskRequest

// NewUpdateProcedureTaskRequest instantiates a new UpdateProcedureTaskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProcedureTaskRequest() *UpdateProcedureTaskRequest {
	this := UpdateProcedureTaskRequest{}
	return &this
}

// NewUpdateProcedureTaskRequestWithDefaults instantiates a new UpdateProcedureTaskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProcedureTaskRequestWithDefaults() *UpdateProcedureTaskRequest {
	this := UpdateProcedureTaskRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateProcedureTaskRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateProcedureTaskRequest) SetDescription(v string) {
	o.Description = &v
}

// GetProcedureId returns the ProcedureId field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetProcedureId() int32 {
	if o == nil || IsNil(o.ProcedureId) {
		var ret int32
		return ret
	}
	return *o.ProcedureId
}

// GetProcedureIdOk returns a tuple with the ProcedureId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetProcedureIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcedureId) {
		return nil, false
	}
	return o.ProcedureId, true
}

// HasProcedureId returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasProcedureId() bool {
	if o != nil && !IsNil(o.ProcedureId) {
		return true
	}

	return false
}

// SetProcedureId gets a reference to the given int32 and assigns it to the ProcedureId field.
func (o *UpdateProcedureTaskRequest) SetProcedureId(v int32) {
	o.ProcedureId = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *UpdateProcedureTaskRequest) SetPosition(v int32) {
	o.Position = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetDueDate() string {
	if o == nil || IsNil(o.DueDate) {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetDueDateOk() (*string, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *UpdateProcedureTaskRequest) SetDueDate(v string) {
	o.DueDate = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *UpdateProcedureTaskRequest) SetPriority(v string) {
	o.Priority = &v
}

// GetAssignedUsers returns the AssignedUsers field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetAssignedUsers() []int32 {
	if o == nil || IsNil(o.AssignedUsers) {
		var ret []int32
		return ret
	}
	return o.AssignedUsers
}

// GetAssignedUsersOk returns a tuple with the AssignedUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetAssignedUsersOk() ([]int32, bool) {
	if o == nil || IsNil(o.AssignedUsers) {
		return nil, false
	}
	return o.AssignedUsers, true
}

// HasAssignedUsers returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasAssignedUsers() bool {
	if o != nil && !IsNil(o.AssignedUsers) {
		return true
	}

	return false
}

// SetAssignedUsers gets a reference to the given []int32 and assigns it to the AssignedUsers field.
func (o *UpdateProcedureTaskRequest) SetAssignedUsers(v []int32) {
	o.AssignedUsers = v
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *UpdateProcedureTaskRequest) SetOptional(v bool) {
	o.Optional = &v
}

// GetParentTaskId returns the ParentTaskId field value if set, zero value otherwise.
func (o *UpdateProcedureTaskRequest) GetParentTaskId() int32 {
	if o == nil || IsNil(o.ParentTaskId) {
		var ret int32
		return ret
	}
	return *o.ParentTaskId
}

// GetParentTaskIdOk returns a tuple with the ParentTaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureTaskRequest) GetParentTaskIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ParentTaskId) {
		return nil, false
	}
	return o.ParentTaskId, true
}

// HasParentTaskId returns a boolean if a field has been set.
func (o *UpdateProcedureTaskRequest) HasParentTaskId() bool {
	if o != nil && !IsNil(o.ParentTaskId) {
		return true
	}

	return false
}

// SetParentTaskId gets a reference to the given int32 and assigns it to the ParentTaskId field.
func (o *UpdateProcedureTaskRequest) SetParentTaskId(v int32) {
	o.ParentTaskId = &v
}

func (o UpdateProcedureTaskRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProcedureTaskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ProcedureId) {
		toSerialize["procedure_id"] = o.ProcedureId
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.DueDate) {
		toSerialize["due_date"] = o.DueDate
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.AssignedUsers) {
		toSerialize["assigned_users"] = o.AssignedUsers
	}
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	if !IsNil(o.ParentTaskId) {
		toSerialize["parent_task_id"] = o.ParentTaskId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateProcedureTaskRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateProcedureTaskRequest := _UpdateProcedureTaskRequest{}

	err = json.Unmarshal(data, &varUpdateProcedureTaskRequest)

	if err != nil {
		return err
	}

	*o = UpdateProcedureTaskRequest(varUpdateProcedureTaskRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "procedure_id")
		delete(additionalProperties, "position")
		delete(additionalProperties, "due_date")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "assigned_users")
		delete(additionalProperties, "optional")
		delete(additionalProperties, "parent_task_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateProcedureTaskRequest struct {
	value *UpdateProcedureTaskRequest
	isSet bool
}

func (v NullableUpdateProcedureTaskRequest) Get() *UpdateProcedureTaskRequest {
	return v.value
}

func (v *NullableUpdateProcedureTaskRequest) Set(val *UpdateProcedureTaskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProcedureTaskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProcedureTaskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProcedureTaskRequest(val *UpdateProcedureTaskRequest) *NullableUpdateProcedureTaskRequest {
	return &NullableUpdateProcedureTaskRequest{value: val, isSet: true}
}

func (v NullableUpdateProcedureTaskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProcedureTaskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
