/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
	"time"
)

// checks if the Vlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vlan{}

// Vlan Virtual Local Area Network (VLAN) configuration.
type Vlan struct {
	// The unique identifier for the VLAN.
	Id *int64 `json:"id,omitempty"`
	// Human-readable VLAN name
	Name *string `json:"name,omitempty"`
	// URL-friendly identifier
	Slug *string `json:"slug,omitempty"`
	// Numeric VLAN (1-4094)
	VlanId *int64 `json:"vlan_id,omitempty"`
	// Optional description
	Description *string `json:"description,omitempty"`
	// Rich-text notes
	Notes *string `json:"notes,omitempty"`
	// The identifier of the company that owns this VLAN.
	CompanyId *int64 `json:"company_id,omitempty"`
	// Zone (nullable)
	VlanZoneId *int64 `json:"vlan_zone_id,omitempty"`
	// The status list item ID for this VLAN.
	StatusListItemId *int64 `json:"status_list_item_id,omitempty"`
	// The role list item ID for this VLAN.
	RoleListItemId *int64 `json:"role_list_item_id,omitempty"`
	// The date and time when the VLAN was archived. Null if not archived.
	ArchivedAt *time.Time `json:"archived_at,omitempty"`
	// The date and time when the VLAN was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The date and time when the VLAN was last updated.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Number of networks currently assigned to this VLAN.
	NetworksCount *int64 `json:"networks_count,omitempty"`
	// Link to VLAN in the web UI
	Url                  *string `json:"url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Vlan Vlan

// NewVlan instantiates a new Vlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVlan() *Vlan {
	this := Vlan{}
	return &this
}

// NewVlanWithDefaults instantiates a new Vlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVlanWithDefaults() *Vlan {
	this := Vlan{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Vlan) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Vlan) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Vlan) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Vlan) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Vlan) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Vlan) SetName(v string) {
	o.Name = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *Vlan) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *Vlan) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *Vlan) SetSlug(v string) {
	o.Slug = &v
}

// GetVlanId returns the VlanId field value if set, zero value otherwise.
func (o *Vlan) GetVlanId() int64 {
	if o == nil || IsNil(o.VlanId) {
		var ret int64
		return ret
	}
	return *o.VlanId
}

// GetVlanIdOk returns a tuple with the VlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetVlanIdOk() (*int64, bool) {
	if o == nil || IsNil(o.VlanId) {
		return nil, false
	}
	return o.VlanId, true
}

// HasVlanId returns a boolean if a field has been set.
func (o *Vlan) HasVlanId() bool {
	if o != nil && !IsNil(o.VlanId) {
		return true
	}

	return false
}

// SetVlanId gets a reference to the given int64 and assigns it to the VlanId field.
func (o *Vlan) SetVlanId(v int64) {
	o.VlanId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Vlan) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Vlan) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Vlan) SetDescription(v string) {
	o.Description = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Vlan) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Vlan) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *Vlan) SetNotes(v string) {
	o.Notes = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *Vlan) GetCompanyId() int64 {
	if o == nil || IsNil(o.CompanyId) {
		var ret int64
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetCompanyIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *Vlan) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int64 and assigns it to the CompanyId field.
func (o *Vlan) SetCompanyId(v int64) {
	o.CompanyId = &v
}

// GetVlanZoneId returns the VlanZoneId field value if set, zero value otherwise.
func (o *Vlan) GetVlanZoneId() int64 {
	if o == nil || IsNil(o.VlanZoneId) {
		var ret int64
		return ret
	}
	return *o.VlanZoneId
}

// GetVlanZoneIdOk returns a tuple with the VlanZoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetVlanZoneIdOk() (*int64, bool) {
	if o == nil || IsNil(o.VlanZoneId) {
		return nil, false
	}
	return o.VlanZoneId, true
}

// HasVlanZoneId returns a boolean if a field has been set.
func (o *Vlan) HasVlanZoneId() bool {
	if o != nil && !IsNil(o.VlanZoneId) {
		return true
	}

	return false
}

// SetVlanZoneId gets a reference to the given int64 and assigns it to the VlanZoneId field.
func (o *Vlan) SetVlanZoneId(v int64) {
	o.VlanZoneId = &v
}

// GetStatusListItemId returns the StatusListItemId field value if set, zero value otherwise.
func (o *Vlan) GetStatusListItemId() int64 {
	if o == nil || IsNil(o.StatusListItemId) {
		var ret int64
		return ret
	}
	return *o.StatusListItemId
}

// GetStatusListItemIdOk returns a tuple with the StatusListItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetStatusListItemIdOk() (*int64, bool) {
	if o == nil || IsNil(o.StatusListItemId) {
		return nil, false
	}
	return o.StatusListItemId, true
}

// HasStatusListItemId returns a boolean if a field has been set.
func (o *Vlan) HasStatusListItemId() bool {
	if o != nil && !IsNil(o.StatusListItemId) {
		return true
	}

	return false
}

// SetStatusListItemId gets a reference to the given int64 and assigns it to the StatusListItemId field.
func (o *Vlan) SetStatusListItemId(v int64) {
	o.StatusListItemId = &v
}

// GetRoleListItemId returns the RoleListItemId field value if set, zero value otherwise.
func (o *Vlan) GetRoleListItemId() int64 {
	if o == nil || IsNil(o.RoleListItemId) {
		var ret int64
		return ret
	}
	return *o.RoleListItemId
}

// GetRoleListItemIdOk returns a tuple with the RoleListItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetRoleListItemIdOk() (*int64, bool) {
	if o == nil || IsNil(o.RoleListItemId) {
		return nil, false
	}
	return o.RoleListItemId, true
}

// HasRoleListItemId returns a boolean if a field has been set.
func (o *Vlan) HasRoleListItemId() bool {
	if o != nil && !IsNil(o.RoleListItemId) {
		return true
	}

	return false
}

// SetRoleListItemId gets a reference to the given int64 and assigns it to the RoleListItemId field.
func (o *Vlan) SetRoleListItemId(v int64) {
	o.RoleListItemId = &v
}

// GetArchivedAt returns the ArchivedAt field value if set, zero value otherwise.
func (o *Vlan) GetArchivedAt() time.Time {
	if o == nil || IsNil(o.ArchivedAt) {
		var ret time.Time
		return ret
	}
	return *o.ArchivedAt
}

// GetArchivedAtOk returns a tuple with the ArchivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetArchivedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ArchivedAt) {
		return nil, false
	}
	return o.ArchivedAt, true
}

// HasArchivedAt returns a boolean if a field has been set.
func (o *Vlan) HasArchivedAt() bool {
	if o != nil && !IsNil(o.ArchivedAt) {
		return true
	}

	return false
}

// SetArchivedAt gets a reference to the given time.Time and assigns it to the ArchivedAt field.
func (o *Vlan) SetArchivedAt(v time.Time) {
	o.ArchivedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Vlan) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Vlan) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Vlan) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Vlan) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Vlan) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Vlan) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetNetworksCount returns the NetworksCount field value if set, zero value otherwise.
func (o *Vlan) GetNetworksCount() int64 {
	if o == nil || IsNil(o.NetworksCount) {
		var ret int64
		return ret
	}
	return *o.NetworksCount
}

// GetNetworksCountOk returns a tuple with the NetworksCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetNetworksCountOk() (*int64, bool) {
	if o == nil || IsNil(o.NetworksCount) {
		return nil, false
	}
	return o.NetworksCount, true
}

// HasNetworksCount returns a boolean if a field has been set.
func (o *Vlan) HasNetworksCount() bool {
	if o != nil && !IsNil(o.NetworksCount) {
		return true
	}

	return false
}

// SetNetworksCount gets a reference to the given int64 and assigns it to the NetworksCount field.
func (o *Vlan) SetNetworksCount(v int64) {
	o.NetworksCount = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Vlan) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vlan) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Vlan) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Vlan) SetUrl(v string) {
	o.Url = &v
}

func (o Vlan) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.VlanId) {
		toSerialize["vlan_id"] = o.VlanId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.CompanyId) {
		toSerialize["company_id"] = o.CompanyId
	}
	if !IsNil(o.VlanZoneId) {
		toSerialize["vlan_zone_id"] = o.VlanZoneId
	}
	if !IsNil(o.StatusListItemId) {
		toSerialize["status_list_item_id"] = o.StatusListItemId
	}
	if !IsNil(o.RoleListItemId) {
		toSerialize["role_list_item_id"] = o.RoleListItemId
	}
	if !IsNil(o.ArchivedAt) {
		toSerialize["archived_at"] = o.ArchivedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.NetworksCount) {
		toSerialize["networks_count"] = o.NetworksCount
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Vlan) UnmarshalJSON(data []byte) (err error) {
	varVlan := _Vlan{}

	err = json.Unmarshal(data, &varVlan)

	if err != nil {
		return err
	}

	*o = Vlan(varVlan)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "vlan_id")
		delete(additionalProperties, "description")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "company_id")
		delete(additionalProperties, "vlan_zone_id")
		delete(additionalProperties, "status_list_item_id")
		delete(additionalProperties, "role_list_item_id")
		delete(additionalProperties, "archived_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "networks_count")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVlan struct {
	value *Vlan
	isSet bool
}

func (v NullableVlan) Get() *Vlan {
	return v.value
}

func (v *NullableVlan) Set(val *Vlan) {
	v.value = val
	v.isSet = true
}

func (v NullableVlan) IsSet() bool {
	return v.isSet
}

func (v *NullableVlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVlan(val *Vlan) *NullableVlan {
	return &NullableVlan{value: val, isSet: true}
}

func (v NullableVlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
