/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateListRequestListListItemsAttributesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateListRequestListListItemsAttributesInner{}

// CreateListRequestListListItemsAttributesInner struct for CreateListRequestListListItemsAttributesInner
type CreateListRequestListListItemsAttributesInner struct {
	// Name of the list item
	Name                 string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _CreateListRequestListListItemsAttributesInner CreateListRequestListListItemsAttributesInner

// NewCreateListRequestListListItemsAttributesInner instantiates a new CreateListRequestListListItemsAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateListRequestListListItemsAttributesInner(name string) *CreateListRequestListListItemsAttributesInner {
	this := CreateListRequestListListItemsAttributesInner{}
	this.Name = name
	return &this
}

// NewCreateListRequestListListItemsAttributesInnerWithDefaults instantiates a new CreateListRequestListListItemsAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateListRequestListListItemsAttributesInnerWithDefaults() *CreateListRequestListListItemsAttributesInner {
	this := CreateListRequestListListItemsAttributesInner{}
	return &this
}

// GetName returns the Name field value
func (o *CreateListRequestListListItemsAttributesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateListRequestListListItemsAttributesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateListRequestListListItemsAttributesInner) SetName(v string) {
	o.Name = v
}

func (o CreateListRequestListListItemsAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateListRequestListListItemsAttributesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateListRequestListListItemsAttributesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateListRequestListListItemsAttributesInner := _CreateListRequestListListItemsAttributesInner{}

	err = json.Unmarshal(data, &varCreateListRequestListListItemsAttributesInner)

	if err != nil {
		return err
	}

	*o = CreateListRequestListListItemsAttributesInner(varCreateListRequestListListItemsAttributesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateListRequestListListItemsAttributesInner struct {
	value *CreateListRequestListListItemsAttributesInner
	isSet bool
}

func (v NullableCreateListRequestListListItemsAttributesInner) Get() *CreateListRequestListListItemsAttributesInner {
	return v.value
}

func (v *NullableCreateListRequestListListItemsAttributesInner) Set(val *CreateListRequestListListItemsAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateListRequestListListItemsAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateListRequestListListItemsAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateListRequestListListItemsAttributesInner(val *CreateListRequestListListItemsAttributesInner) *NullableCreateListRequestListListItemsAttributesInner {
	return &NullableCreateListRequestListListItemsAttributesInner{value: val, isSet: true}
}

func (v NullableCreateListRequestListListItemsAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateListRequestListListItemsAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
