/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the CreateFlagTypeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFlagTypeRequest{}

// CreateFlagTypeRequest struct for CreateFlagTypeRequest
type CreateFlagTypeRequest struct {
	FlagType             *CreateFlagTypeRequestFlagType `json:"flag_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateFlagTypeRequest CreateFlagTypeRequest

// NewCreateFlagTypeRequest instantiates a new CreateFlagTypeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFlagTypeRequest() *CreateFlagTypeRequest {
	this := CreateFlagTypeRequest{}
	return &this
}

// NewCreateFlagTypeRequestWithDefaults instantiates a new CreateFlagTypeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFlagTypeRequestWithDefaults() *CreateFlagTypeRequest {
	this := CreateFlagTypeRequest{}
	return &this
}

// GetFlagType returns the FlagType field value if set, zero value otherwise.
func (o *CreateFlagTypeRequest) GetFlagType() CreateFlagTypeRequestFlagType {
	if o == nil || IsNil(o.FlagType) {
		var ret CreateFlagTypeRequestFlagType
		return ret
	}
	return *o.FlagType
}

// GetFlagTypeOk returns a tuple with the FlagType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFlagTypeRequest) GetFlagTypeOk() (*CreateFlagTypeRequestFlagType, bool) {
	if o == nil || IsNil(o.FlagType) {
		return nil, false
	}
	return o.FlagType, true
}

// HasFlagType returns a boolean if a field has been set.
func (o *CreateFlagTypeRequest) HasFlagType() bool {
	if o != nil && !IsNil(o.FlagType) {
		return true
	}

	return false
}

// SetFlagType gets a reference to the given CreateFlagTypeRequestFlagType and assigns it to the FlagType field.
func (o *CreateFlagTypeRequest) SetFlagType(v CreateFlagTypeRequestFlagType) {
	o.FlagType = &v
}

func (o CreateFlagTypeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFlagTypeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FlagType) {
		toSerialize["flag_type"] = o.FlagType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateFlagTypeRequest) UnmarshalJSON(data []byte) (err error) {
	varCreateFlagTypeRequest := _CreateFlagTypeRequest{}

	err = json.Unmarshal(data, &varCreateFlagTypeRequest)

	if err != nil {
		return err
	}

	*o = CreateFlagTypeRequest(varCreateFlagTypeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "flag_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateFlagTypeRequest struct {
	value *CreateFlagTypeRequest
	isSet bool
}

func (v NullableCreateFlagTypeRequest) Get() *CreateFlagTypeRequest {
	return v.value
}

func (v *NullableCreateFlagTypeRequest) Set(val *CreateFlagTypeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFlagTypeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFlagTypeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFlagTypeRequest(val *CreateFlagTypeRequest) *NullableCreateFlagTypeRequest {
	return &NullableCreateFlagTypeRequest{value: val, isSet: true}
}

func (v NullableCreateFlagTypeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFlagTypeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
