/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the GetFlags200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFlags200Response{}

// GetFlags200Response struct for GetFlags200Response
type GetFlags200Response struct {
	Flags                []Flag `json:"flags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetFlags200Response GetFlags200Response

// NewGetFlags200Response instantiates a new GetFlags200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFlags200Response() *GetFlags200Response {
	this := GetFlags200Response{}
	return &this
}

// NewGetFlags200ResponseWithDefaults instantiates a new GetFlags200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFlags200ResponseWithDefaults() *GetFlags200Response {
	this := GetFlags200Response{}
	return &this
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *GetFlags200Response) GetFlags() []Flag {
	if o == nil || IsNil(o.Flags) {
		var ret []Flag
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFlags200Response) GetFlagsOk() ([]Flag, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *GetFlags200Response) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []Flag and assigns it to the Flags field.
func (o *GetFlags200Response) SetFlags(v []Flag) {
	o.Flags = v
}

func (o GetFlags200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFlags200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetFlags200Response) UnmarshalJSON(data []byte) (err error) {
	varGetFlags200Response := _GetFlags200Response{}

	err = json.Unmarshal(data, &varGetFlags200Response)

	if err != nil {
		return err
	}

	*o = GetFlags200Response(varGetFlags200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "flags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetFlags200Response struct {
	value *GetFlags200Response
	isSet bool
}

func (v NullableGetFlags200Response) Get() *GetFlags200Response {
	return v.value
}

func (v *NullableGetFlags200Response) Set(val *GetFlags200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFlags200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFlags200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFlags200Response(val *GetFlags200Response) *NullableGetFlags200Response {
	return &NullableGetFlags200Response{value: val, isSet: true}
}

func (v NullableGetFlags200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFlags200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
