/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PostExportsRequestExport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostExportsRequestExport{}

// PostExportsRequestExport struct for PostExportsRequestExport
type PostExportsRequestExport struct {
	// Required. The export format: 'pdf' for formatted PDF document or 'csv' for raw data export.
	Format string `json:"format"`
	// Required. The ID of the company to export.
	CompanyId int64 `json:"company_id"`
	// Required. Whether to include passwords in the export.
	IncludePasswords bool `json:"include_passwords"`
	// Required. Whether to include websites in the export.
	IncludeWebsites bool `json:"include_websites"`
	// PDF only. Whether to include knowledge base articles. Defaults to false if not provided.
	IncludeArticles *bool `json:"include_articles,omitempty"`
	// PDF only. Whether to include archived knowledge base articles. Defaults to false if not provided.
	IncludeArchivedArticles *bool `json:"include_archived_articles,omitempty"`
	// PDF only. Whether to include archived passwords. Defaults to false if not provided.
	IncludeArchivedPasswords *bool `json:"include_archived_passwords,omitempty"`
	// PDF only. Whether to include archived websites. Defaults to false if not provided.
	IncludeArchivedWebsites *bool `json:"include_archived_websites,omitempty"`
	// PDF only. Whether to include archived assets. Defaults to false if not provided.
	IncludeArchivedAssets *bool `json:"include_archived_assets,omitempty"`
	// PDF only. Array of asset layout IDs to filter which asset types to include. If empty or not provided, all asset layouts are included.
	AssetLayoutIds       []int64 `json:"asset_layout_ids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PostExportsRequestExport PostExportsRequestExport

// NewPostExportsRequestExport instantiates a new PostExportsRequestExport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostExportsRequestExport(format string, companyId int64, includePasswords bool, includeWebsites bool) *PostExportsRequestExport {
	this := PostExportsRequestExport{}
	this.Format = format
	this.CompanyId = companyId
	this.IncludePasswords = includePasswords
	this.IncludeWebsites = includeWebsites
	return &this
}

// NewPostExportsRequestExportWithDefaults instantiates a new PostExportsRequestExport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostExportsRequestExportWithDefaults() *PostExportsRequestExport {
	this := PostExportsRequestExport{}
	return &this
}

// GetFormat returns the Format field value
func (o *PostExportsRequestExport) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *PostExportsRequestExport) SetFormat(v string) {
	o.Format = v
}

// GetCompanyId returns the CompanyId field value
func (o *PostExportsRequestExport) GetCompanyId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetCompanyIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *PostExportsRequestExport) SetCompanyId(v int64) {
	o.CompanyId = v
}

// GetIncludePasswords returns the IncludePasswords field value
func (o *PostExportsRequestExport) GetIncludePasswords() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludePasswords
}

// GetIncludePasswordsOk returns a tuple with the IncludePasswords field value
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludePasswordsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludePasswords, true
}

// SetIncludePasswords sets field value
func (o *PostExportsRequestExport) SetIncludePasswords(v bool) {
	o.IncludePasswords = v
}

// GetIncludeWebsites returns the IncludeWebsites field value
func (o *PostExportsRequestExport) GetIncludeWebsites() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeWebsites
}

// GetIncludeWebsitesOk returns a tuple with the IncludeWebsites field value
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludeWebsitesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeWebsites, true
}

// SetIncludeWebsites sets field value
func (o *PostExportsRequestExport) SetIncludeWebsites(v bool) {
	o.IncludeWebsites = v
}

// GetIncludeArticles returns the IncludeArticles field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetIncludeArticles() bool {
	if o == nil || IsNil(o.IncludeArticles) {
		var ret bool
		return ret
	}
	return *o.IncludeArticles
}

// GetIncludeArticlesOk returns a tuple with the IncludeArticles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludeArticlesOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeArticles) {
		return nil, false
	}
	return o.IncludeArticles, true
}

// HasIncludeArticles returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasIncludeArticles() bool {
	if o != nil && !IsNil(o.IncludeArticles) {
		return true
	}

	return false
}

// SetIncludeArticles gets a reference to the given bool and assigns it to the IncludeArticles field.
func (o *PostExportsRequestExport) SetIncludeArticles(v bool) {
	o.IncludeArticles = &v
}

// GetIncludeArchivedArticles returns the IncludeArchivedArticles field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetIncludeArchivedArticles() bool {
	if o == nil || IsNil(o.IncludeArchivedArticles) {
		var ret bool
		return ret
	}
	return *o.IncludeArchivedArticles
}

// GetIncludeArchivedArticlesOk returns a tuple with the IncludeArchivedArticles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludeArchivedArticlesOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeArchivedArticles) {
		return nil, false
	}
	return o.IncludeArchivedArticles, true
}

// HasIncludeArchivedArticles returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasIncludeArchivedArticles() bool {
	if o != nil && !IsNil(o.IncludeArchivedArticles) {
		return true
	}

	return false
}

// SetIncludeArchivedArticles gets a reference to the given bool and assigns it to the IncludeArchivedArticles field.
func (o *PostExportsRequestExport) SetIncludeArchivedArticles(v bool) {
	o.IncludeArchivedArticles = &v
}

// GetIncludeArchivedPasswords returns the IncludeArchivedPasswords field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetIncludeArchivedPasswords() bool {
	if o == nil || IsNil(o.IncludeArchivedPasswords) {
		var ret bool
		return ret
	}
	return *o.IncludeArchivedPasswords
}

// GetIncludeArchivedPasswordsOk returns a tuple with the IncludeArchivedPasswords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludeArchivedPasswordsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeArchivedPasswords) {
		return nil, false
	}
	return o.IncludeArchivedPasswords, true
}

// HasIncludeArchivedPasswords returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasIncludeArchivedPasswords() bool {
	if o != nil && !IsNil(o.IncludeArchivedPasswords) {
		return true
	}

	return false
}

// SetIncludeArchivedPasswords gets a reference to the given bool and assigns it to the IncludeArchivedPasswords field.
func (o *PostExportsRequestExport) SetIncludeArchivedPasswords(v bool) {
	o.IncludeArchivedPasswords = &v
}

// GetIncludeArchivedWebsites returns the IncludeArchivedWebsites field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetIncludeArchivedWebsites() bool {
	if o == nil || IsNil(o.IncludeArchivedWebsites) {
		var ret bool
		return ret
	}
	return *o.IncludeArchivedWebsites
}

// GetIncludeArchivedWebsitesOk returns a tuple with the IncludeArchivedWebsites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludeArchivedWebsitesOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeArchivedWebsites) {
		return nil, false
	}
	return o.IncludeArchivedWebsites, true
}

// HasIncludeArchivedWebsites returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasIncludeArchivedWebsites() bool {
	if o != nil && !IsNil(o.IncludeArchivedWebsites) {
		return true
	}

	return false
}

// SetIncludeArchivedWebsites gets a reference to the given bool and assigns it to the IncludeArchivedWebsites field.
func (o *PostExportsRequestExport) SetIncludeArchivedWebsites(v bool) {
	o.IncludeArchivedWebsites = &v
}

// GetIncludeArchivedAssets returns the IncludeArchivedAssets field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetIncludeArchivedAssets() bool {
	if o == nil || IsNil(o.IncludeArchivedAssets) {
		var ret bool
		return ret
	}
	return *o.IncludeArchivedAssets
}

// GetIncludeArchivedAssetsOk returns a tuple with the IncludeArchivedAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludeArchivedAssetsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeArchivedAssets) {
		return nil, false
	}
	return o.IncludeArchivedAssets, true
}

// HasIncludeArchivedAssets returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasIncludeArchivedAssets() bool {
	if o != nil && !IsNil(o.IncludeArchivedAssets) {
		return true
	}

	return false
}

// SetIncludeArchivedAssets gets a reference to the given bool and assigns it to the IncludeArchivedAssets field.
func (o *PostExportsRequestExport) SetIncludeArchivedAssets(v bool) {
	o.IncludeArchivedAssets = &v
}

// GetAssetLayoutIds returns the AssetLayoutIds field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetAssetLayoutIds() []int64 {
	if o == nil || IsNil(o.AssetLayoutIds) {
		var ret []int64
		return ret
	}
	return o.AssetLayoutIds
}

// GetAssetLayoutIdsOk returns a tuple with the AssetLayoutIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetAssetLayoutIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.AssetLayoutIds) {
		return nil, false
	}
	return o.AssetLayoutIds, true
}

// HasAssetLayoutIds returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasAssetLayoutIds() bool {
	if o != nil && !IsNil(o.AssetLayoutIds) {
		return true
	}

	return false
}

// SetAssetLayoutIds gets a reference to the given []int64 and assigns it to the AssetLayoutIds field.
func (o *PostExportsRequestExport) SetAssetLayoutIds(v []int64) {
	o.AssetLayoutIds = v
}

func (o PostExportsRequestExport) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostExportsRequestExport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["format"] = o.Format
	toSerialize["company_id"] = o.CompanyId
	toSerialize["include_passwords"] = o.IncludePasswords
	toSerialize["include_websites"] = o.IncludeWebsites
	if !IsNil(o.IncludeArticles) {
		toSerialize["include_articles"] = o.IncludeArticles
	}
	if !IsNil(o.IncludeArchivedArticles) {
		toSerialize["include_archived_articles"] = o.IncludeArchivedArticles
	}
	if !IsNil(o.IncludeArchivedPasswords) {
		toSerialize["include_archived_passwords"] = o.IncludeArchivedPasswords
	}
	if !IsNil(o.IncludeArchivedWebsites) {
		toSerialize["include_archived_websites"] = o.IncludeArchivedWebsites
	}
	if !IsNil(o.IncludeArchivedAssets) {
		toSerialize["include_archived_assets"] = o.IncludeArchivedAssets
	}
	if !IsNil(o.AssetLayoutIds) {
		toSerialize["asset_layout_ids"] = o.AssetLayoutIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostExportsRequestExport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"format",
		"company_id",
		"include_passwords",
		"include_websites",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostExportsRequestExport := _PostExportsRequestExport{}

	err = json.Unmarshal(data, &varPostExportsRequestExport)

	if err != nil {
		return err
	}

	*o = PostExportsRequestExport(varPostExportsRequestExport)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "format")
		delete(additionalProperties, "company_id")
		delete(additionalProperties, "include_passwords")
		delete(additionalProperties, "include_websites")
		delete(additionalProperties, "include_articles")
		delete(additionalProperties, "include_archived_articles")
		delete(additionalProperties, "include_archived_passwords")
		delete(additionalProperties, "include_archived_websites")
		delete(additionalProperties, "include_archived_assets")
		delete(additionalProperties, "asset_layout_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePostExportsRequestExport struct {
	value *PostExportsRequestExport
	isSet bool
}

func (v NullablePostExportsRequestExport) Get() *PostExportsRequestExport {
	return v.value
}

func (v *NullablePostExportsRequestExport) Set(val *PostExportsRequestExport) {
	v.value = val
	v.isSet = true
}

func (v NullablePostExportsRequestExport) IsSet() bool {
	return v.isSet
}

func (v *NullablePostExportsRequestExport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostExportsRequestExport(val *PostExportsRequestExport) *NullablePostExportsRequestExport {
	return &NullablePostExportsRequestExport{value: val, isSet: true}
}

func (v NullablePostExportsRequestExport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostExportsRequestExport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
