/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PostRackStorageItemsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostRackStorageItemsRequest{}

// PostRackStorageItemsRequest struct for PostRackStorageItemsRequest
type PostRackStorageItemsRequest struct {
	RackStorageItem      RackStorageItem `json:"rack_storage_item"`
	AdditionalProperties map[string]interface{}
}

type _PostRackStorageItemsRequest PostRackStorageItemsRequest

// NewPostRackStorageItemsRequest instantiates a new PostRackStorageItemsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostRackStorageItemsRequest(rackStorageItem RackStorageItem) *PostRackStorageItemsRequest {
	this := PostRackStorageItemsRequest{}
	this.RackStorageItem = rackStorageItem
	return &this
}

// NewPostRackStorageItemsRequestWithDefaults instantiates a new PostRackStorageItemsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostRackStorageItemsRequestWithDefaults() *PostRackStorageItemsRequest {
	this := PostRackStorageItemsRequest{}
	return &this
}

// GetRackStorageItem returns the RackStorageItem field value
func (o *PostRackStorageItemsRequest) GetRackStorageItem() RackStorageItem {
	if o == nil {
		var ret RackStorageItem
		return ret
	}

	return o.RackStorageItem
}

// GetRackStorageItemOk returns a tuple with the RackStorageItem field value
// and a boolean to check if the value has been set.
func (o *PostRackStorageItemsRequest) GetRackStorageItemOk() (*RackStorageItem, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RackStorageItem, true
}

// SetRackStorageItem sets field value
func (o *PostRackStorageItemsRequest) SetRackStorageItem(v RackStorageItem) {
	o.RackStorageItem = v
}

func (o PostRackStorageItemsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostRackStorageItemsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rack_storage_item"] = o.RackStorageItem

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostRackStorageItemsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rack_storage_item",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostRackStorageItemsRequest := _PostRackStorageItemsRequest{}

	err = json.Unmarshal(data, &varPostRackStorageItemsRequest)

	if err != nil {
		return err
	}

	*o = PostRackStorageItemsRequest(varPostRackStorageItemsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rack_storage_item")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePostRackStorageItemsRequest struct {
	value *PostRackStorageItemsRequest
	isSet bool
}

func (v NullablePostRackStorageItemsRequest) Get() *PostRackStorageItemsRequest {
	return v.value
}

func (v *NullablePostRackStorageItemsRequest) Set(val *PostRackStorageItemsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostRackStorageItemsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostRackStorageItemsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostRackStorageItemsRequest(val *PostRackStorageItemsRequest) *NullablePostRackStorageItemsRequest {
	return &NullablePostRackStorageItemsRequest{value: val, isSet: true}
}

func (v NullablePostRackStorageItemsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostRackStorageItemsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
