/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the UpdatePublicPhoto200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePublicPhoto200Response{}

// UpdatePublicPhoto200Response struct for UpdatePublicPhoto200Response
type UpdatePublicPhoto200Response struct {
	PublicPhoto          *PublicPhoto `json:"public_photo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdatePublicPhoto200Response UpdatePublicPhoto200Response

// NewUpdatePublicPhoto200Response instantiates a new UpdatePublicPhoto200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePublicPhoto200Response() *UpdatePublicPhoto200Response {
	this := UpdatePublicPhoto200Response{}
	return &this
}

// NewUpdatePublicPhoto200ResponseWithDefaults instantiates a new UpdatePublicPhoto200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePublicPhoto200ResponseWithDefaults() *UpdatePublicPhoto200Response {
	this := UpdatePublicPhoto200Response{}
	return &this
}

// GetPublicPhoto returns the PublicPhoto field value if set, zero value otherwise.
func (o *UpdatePublicPhoto200Response) GetPublicPhoto() PublicPhoto {
	if o == nil || IsNil(o.PublicPhoto) {
		var ret PublicPhoto
		return ret
	}
	return *o.PublicPhoto
}

// GetPublicPhotoOk returns a tuple with the PublicPhoto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePublicPhoto200Response) GetPublicPhotoOk() (*PublicPhoto, bool) {
	if o == nil || IsNil(o.PublicPhoto) {
		return nil, false
	}
	return o.PublicPhoto, true
}

// HasPublicPhoto returns a boolean if a field has been set.
func (o *UpdatePublicPhoto200Response) HasPublicPhoto() bool {
	if o != nil && !IsNil(o.PublicPhoto) {
		return true
	}

	return false
}

// SetPublicPhoto gets a reference to the given PublicPhoto and assigns it to the PublicPhoto field.
func (o *UpdatePublicPhoto200Response) SetPublicPhoto(v PublicPhoto) {
	o.PublicPhoto = &v
}

func (o UpdatePublicPhoto200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePublicPhoto200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PublicPhoto) {
		toSerialize["public_photo"] = o.PublicPhoto
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdatePublicPhoto200Response) UnmarshalJSON(data []byte) (err error) {
	varUpdatePublicPhoto200Response := _UpdatePublicPhoto200Response{}

	err = json.Unmarshal(data, &varUpdatePublicPhoto200Response)

	if err != nil {
		return err
	}

	*o = UpdatePublicPhoto200Response(varUpdatePublicPhoto200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "public_photo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdatePublicPhoto200Response struct {
	value *UpdatePublicPhoto200Response
	isSet bool
}

func (v NullableUpdatePublicPhoto200Response) Get() *UpdatePublicPhoto200Response {
	return v.value
}

func (v *NullableUpdatePublicPhoto200Response) Set(val *UpdatePublicPhoto200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePublicPhoto200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePublicPhoto200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePublicPhoto200Response(val *UpdatePublicPhoto200Response) *NullableUpdatePublicPhoto200Response {
	return &NullableUpdatePublicPhoto200Response{value: val, isSet: true}
}

func (v NullableUpdatePublicPhoto200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePublicPhoto200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
