/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the CreatePhoto201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePhoto201Response{}

// CreatePhoto201Response struct for CreatePhoto201Response
type CreatePhoto201Response struct {
	Photo                *Photo `json:"photo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreatePhoto201Response CreatePhoto201Response

// NewCreatePhoto201Response instantiates a new CreatePhoto201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePhoto201Response() *CreatePhoto201Response {
	this := CreatePhoto201Response{}
	return &this
}

// NewCreatePhoto201ResponseWithDefaults instantiates a new CreatePhoto201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePhoto201ResponseWithDefaults() *CreatePhoto201Response {
	this := CreatePhoto201Response{}
	return &this
}

// GetPhoto returns the Photo field value if set, zero value otherwise.
func (o *CreatePhoto201Response) GetPhoto() Photo {
	if o == nil || IsNil(o.Photo) {
		var ret Photo
		return ret
	}
	return *o.Photo
}

// GetPhotoOk returns a tuple with the Photo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePhoto201Response) GetPhotoOk() (*Photo, bool) {
	if o == nil || IsNil(o.Photo) {
		return nil, false
	}
	return o.Photo, true
}

// HasPhoto returns a boolean if a field has been set.
func (o *CreatePhoto201Response) HasPhoto() bool {
	if o != nil && !IsNil(o.Photo) {
		return true
	}

	return false
}

// SetPhoto gets a reference to the given Photo and assigns it to the Photo field.
func (o *CreatePhoto201Response) SetPhoto(v Photo) {
	o.Photo = &v
}

func (o CreatePhoto201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePhoto201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Photo) {
		toSerialize["photo"] = o.Photo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreatePhoto201Response) UnmarshalJSON(data []byte) (err error) {
	varCreatePhoto201Response := _CreatePhoto201Response{}

	err = json.Unmarshal(data, &varCreatePhoto201Response)

	if err != nil {
		return err
	}

	*o = CreatePhoto201Response(varCreatePhoto201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "photo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreatePhoto201Response struct {
	value *CreatePhoto201Response
	isSet bool
}

func (v NullableCreatePhoto201Response) Get() *CreatePhoto201Response {
	return v.value
}

func (v *NullableCreatePhoto201Response) Set(val *CreatePhoto201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePhoto201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePhoto201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePhoto201Response(val *CreatePhoto201Response) *NullableCreatePhoto201Response {
	return &NullableCreatePhoto201Response{value: val, isSet: true}
}

func (v NullableCreatePhoto201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePhoto201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
