/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the PostFoldersRequestFolder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostFoldersRequestFolder{}

// PostFoldersRequestFolder struct for PostFoldersRequestFolder
type PostFoldersRequestFolder struct {
	// Name of the folder
	Name *string `json:"name,omitempty"`
	// Icon for the folder
	Icon *string `json:"icon,omitempty"`
	// Description of the folder
	Description *string `json:"description,omitempty"`
	// ID of the parent folder (optional)
	ParentFolderId *int64 `json:"parent_folder_id,omitempty"`
	// ID of the associated company (optional)
	CompanyId            *int64 `json:"company_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PostFoldersRequestFolder PostFoldersRequestFolder

// NewPostFoldersRequestFolder instantiates a new PostFoldersRequestFolder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostFoldersRequestFolder() *PostFoldersRequestFolder {
	this := PostFoldersRequestFolder{}
	return &this
}

// NewPostFoldersRequestFolderWithDefaults instantiates a new PostFoldersRequestFolder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostFoldersRequestFolderWithDefaults() *PostFoldersRequestFolder {
	this := PostFoldersRequestFolder{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PostFoldersRequestFolder) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostFoldersRequestFolder) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PostFoldersRequestFolder) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PostFoldersRequestFolder) SetName(v string) {
	o.Name = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *PostFoldersRequestFolder) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostFoldersRequestFolder) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *PostFoldersRequestFolder) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *PostFoldersRequestFolder) SetIcon(v string) {
	o.Icon = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PostFoldersRequestFolder) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostFoldersRequestFolder) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PostFoldersRequestFolder) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PostFoldersRequestFolder) SetDescription(v string) {
	o.Description = &v
}

// GetParentFolderId returns the ParentFolderId field value if set, zero value otherwise.
func (o *PostFoldersRequestFolder) GetParentFolderId() int64 {
	if o == nil || IsNil(o.ParentFolderId) {
		var ret int64
		return ret
	}
	return *o.ParentFolderId
}

// GetParentFolderIdOk returns a tuple with the ParentFolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostFoldersRequestFolder) GetParentFolderIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ParentFolderId) {
		return nil, false
	}
	return o.ParentFolderId, true
}

// HasParentFolderId returns a boolean if a field has been set.
func (o *PostFoldersRequestFolder) HasParentFolderId() bool {
	if o != nil && !IsNil(o.ParentFolderId) {
		return true
	}

	return false
}

// SetParentFolderId gets a reference to the given int64 and assigns it to the ParentFolderId field.
func (o *PostFoldersRequestFolder) SetParentFolderId(v int64) {
	o.ParentFolderId = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *PostFoldersRequestFolder) GetCompanyId() int64 {
	if o == nil || IsNil(o.CompanyId) {
		var ret int64
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostFoldersRequestFolder) GetCompanyIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *PostFoldersRequestFolder) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int64 and assigns it to the CompanyId field.
func (o *PostFoldersRequestFolder) SetCompanyId(v int64) {
	o.CompanyId = &v
}

func (o PostFoldersRequestFolder) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostFoldersRequestFolder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ParentFolderId) {
		toSerialize["parent_folder_id"] = o.ParentFolderId
	}
	if !IsNil(o.CompanyId) {
		toSerialize["company_id"] = o.CompanyId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostFoldersRequestFolder) UnmarshalJSON(data []byte) (err error) {
	varPostFoldersRequestFolder := _PostFoldersRequestFolder{}

	err = json.Unmarshal(data, &varPostFoldersRequestFolder)

	if err != nil {
		return err
	}

	*o = PostFoldersRequestFolder(varPostFoldersRequestFolder)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "description")
		delete(additionalProperties, "parent_folder_id")
		delete(additionalProperties, "company_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePostFoldersRequestFolder struct {
	value *PostFoldersRequestFolder
	isSet bool
}

func (v NullablePostFoldersRequestFolder) Get() *PostFoldersRequestFolder {
	return v.value
}

func (v *NullablePostFoldersRequestFolder) Set(val *PostFoldersRequestFolder) {
	v.value = val
	v.isSet = true
}

func (v NullablePostFoldersRequestFolder) IsSet() bool {
	return v.isSet
}

func (v *NullablePostFoldersRequestFolder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostFoldersRequestFolder(val *PostFoldersRequestFolder) *NullablePostFoldersRequestFolder {
	return &NullablePostFoldersRequestFolder{value: val, isSet: true}
}

func (v NullablePostFoldersRequestFolder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostFoldersRequestFolder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
