/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
	"fmt"
)

// checks if the MagicDash type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MagicDash{}

// MagicDash struct for MagicDash
type MagicDash struct {
	// The unique identifier for the MagicDash item
	Id int64 `json:"id"`
	// The title of the MagicDash item
	Title string `json:"title"`
	// The message content of the MagicDash item
	Message string `json:"message"`
	// The background shade of the MagicDash item (optional). Can Be null.
	Shade *string `json:"shade,omitempty"`
	// The link associated with the MagicDash item's content (optional). Can Be null.
	ContentLink *string `json:"content_link,omitempty"`
	// The MagicDash item's content (optional). Can Be null.
	Content *string `json:"content,omitempty"`
	// The icon associated with the MagicDash item (optional). Can Be null.
	Icon *string `json:"icon,omitempty"`
	// The URL of the image associated with the MagicDash item (optional). Can Be null.
	ImageUrl *string `json:"image_url,omitempty"`
	// The unique identifier of the associated company
	CompanyId int64 `json:"company_id"`
	// The name of the associated company
	CompanyName          string `json:"company_name"`
	AdditionalProperties map[string]interface{}
}

type _MagicDash MagicDash

// NewMagicDash instantiates a new MagicDash object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMagicDash(id int64, title string, message string, companyId int64, companyName string) *MagicDash {
	this := MagicDash{}
	this.Id = id
	this.Title = title
	this.Message = message
	this.CompanyId = companyId
	this.CompanyName = companyName
	return &this
}

// NewMagicDashWithDefaults instantiates a new MagicDash object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMagicDashWithDefaults() *MagicDash {
	this := MagicDash{}
	return &this
}

// GetId returns the Id field value
func (o *MagicDash) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MagicDash) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MagicDash) SetId(v int64) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *MagicDash) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *MagicDash) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *MagicDash) SetTitle(v string) {
	o.Title = v
}

// GetMessage returns the Message field value
func (o *MagicDash) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *MagicDash) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *MagicDash) SetMessage(v string) {
	o.Message = v
}

// GetShade returns the Shade field value if set, zero value otherwise.
func (o *MagicDash) GetShade() string {
	if o == nil || IsNil(o.Shade) {
		var ret string
		return ret
	}
	return *o.Shade
}

// GetShadeOk returns a tuple with the Shade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagicDash) GetShadeOk() (*string, bool) {
	if o == nil || IsNil(o.Shade) {
		return nil, false
	}
	return o.Shade, true
}

// HasShade returns a boolean if a field has been set.
func (o *MagicDash) HasShade() bool {
	if o != nil && !IsNil(o.Shade) {
		return true
	}

	return false
}

// SetShade gets a reference to the given string and assigns it to the Shade field.
func (o *MagicDash) SetShade(v string) {
	o.Shade = &v
}

// GetContentLink returns the ContentLink field value if set, zero value otherwise.
func (o *MagicDash) GetContentLink() string {
	if o == nil || IsNil(o.ContentLink) {
		var ret string
		return ret
	}
	return *o.ContentLink
}

// GetContentLinkOk returns a tuple with the ContentLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagicDash) GetContentLinkOk() (*string, bool) {
	if o == nil || IsNil(o.ContentLink) {
		return nil, false
	}
	return o.ContentLink, true
}

// HasContentLink returns a boolean if a field has been set.
func (o *MagicDash) HasContentLink() bool {
	if o != nil && !IsNil(o.ContentLink) {
		return true
	}

	return false
}

// SetContentLink gets a reference to the given string and assigns it to the ContentLink field.
func (o *MagicDash) SetContentLink(v string) {
	o.ContentLink = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *MagicDash) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagicDash) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *MagicDash) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *MagicDash) SetContent(v string) {
	o.Content = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *MagicDash) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagicDash) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *MagicDash) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *MagicDash) SetIcon(v string) {
	o.Icon = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *MagicDash) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MagicDash) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *MagicDash) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *MagicDash) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetCompanyId returns the CompanyId field value
func (o *MagicDash) GetCompanyId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *MagicDash) GetCompanyIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *MagicDash) SetCompanyId(v int64) {
	o.CompanyId = v
}

// GetCompanyName returns the CompanyName field value
func (o *MagicDash) GetCompanyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value
// and a boolean to check if the value has been set.
func (o *MagicDash) GetCompanyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyName, true
}

// SetCompanyName sets field value
func (o *MagicDash) SetCompanyName(v string) {
	o.CompanyName = v
}

func (o MagicDash) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MagicDash) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title
	toSerialize["message"] = o.Message
	if !IsNil(o.Shade) {
		toSerialize["shade"] = o.Shade
	}
	if !IsNil(o.ContentLink) {
		toSerialize["content_link"] = o.ContentLink
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	toSerialize["company_id"] = o.CompanyId
	toSerialize["company_name"] = o.CompanyName

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MagicDash) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"title",
		"message",
		"company_id",
		"company_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMagicDash := _MagicDash{}

	err = json.Unmarshal(data, &varMagicDash)

	if err != nil {
		return err
	}

	*o = MagicDash(varMagicDash)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		delete(additionalProperties, "message")
		delete(additionalProperties, "shade")
		delete(additionalProperties, "content_link")
		delete(additionalProperties, "content")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "image_url")
		delete(additionalProperties, "company_id")
		delete(additionalProperties, "company_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMagicDash struct {
	value *MagicDash
	isSet bool
}

func (v NullableMagicDash) Get() *MagicDash {
	return v.value
}

func (v *NullableMagicDash) Set(val *MagicDash) {
	v.value = val
	v.isSet = true
}

func (v NullableMagicDash) IsSet() bool {
	return v.isSet
}

func (v *NullableMagicDash) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMagicDash(val *MagicDash) *NullableMagicDash {
	return &NullableMagicDash{value: val, isSet: true}
}

func (v NullableMagicDash) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMagicDash) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
