/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Expiration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Expiration{}

// Expiration struct for Expiration
type Expiration struct {
	// The unique identifier for the expiration
	Id float32 `json:"id"`
	// The expiration date
	Date string `json:"date"`
	// The type of object associated with the expiration (e.g., Website)
	ExpirationableType string `json:"expirationable_type"`
	// The ID of the object associated with the expiration
	ExpirationableId float32 `json:"expirationable_id"`
	// The account ID associated with the expiration
	AccountId float32 `json:"account_id"`
	// The company ID associated with the expiration
	CompanyId float32 `json:"company_id"`
	// The asset layout field ID associated with the expiration (if any), Can be null.
	AssetLayoutFieldId *float32 `json:"asset_layout_field_id,omitempty"`
	// The sync ID associated with the expiration (if any). Can be null
	SyncId *float32 `json:"sync_id,omitempty"`
	// The timestamp when the expiration was discarded (if any). Can be null.
	DiscardedAt *time.Time `json:"discarded_at,omitempty"`
	// The timestamp when the expiration was created
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The timestamp when the expiration was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// The type of expiration (e.g., domain)
	ExpirationType string `json:"expiration_type"`
	// The asset field ID associated with the expiration (if any). Can be null.
	AssetFieldId         *float32 `json:"asset_field_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Expiration Expiration

// NewExpiration instantiates a new Expiration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpiration(id float32, date string, expirationableType string, expirationableId float32, accountId float32, companyId float32, expirationType string) *Expiration {
	this := Expiration{}
	this.Id = id
	this.Date = date
	this.ExpirationableType = expirationableType
	this.ExpirationableId = expirationableId
	this.AccountId = accountId
	this.CompanyId = companyId
	this.ExpirationType = expirationType
	return &this
}

// NewExpirationWithDefaults instantiates a new Expiration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpirationWithDefaults() *Expiration {
	this := Expiration{}
	return &this
}

// GetId returns the Id field value
func (o *Expiration) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Expiration) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Expiration) SetId(v float32) {
	o.Id = v
}

// GetDate returns the Date field value
func (o *Expiration) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *Expiration) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *Expiration) SetDate(v string) {
	o.Date = v
}

// GetExpirationableType returns the ExpirationableType field value
func (o *Expiration) GetExpirationableType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpirationableType
}

// GetExpirationableTypeOk returns a tuple with the ExpirationableType field value
// and a boolean to check if the value has been set.
func (o *Expiration) GetExpirationableTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpirationableType, true
}

// SetExpirationableType sets field value
func (o *Expiration) SetExpirationableType(v string) {
	o.ExpirationableType = v
}

// GetExpirationableId returns the ExpirationableId field value
func (o *Expiration) GetExpirationableId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ExpirationableId
}

// GetExpirationableIdOk returns a tuple with the ExpirationableId field value
// and a boolean to check if the value has been set.
func (o *Expiration) GetExpirationableIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpirationableId, true
}

// SetExpirationableId sets field value
func (o *Expiration) SetExpirationableId(v float32) {
	o.ExpirationableId = v
}

// GetAccountId returns the AccountId field value
func (o *Expiration) GetAccountId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *Expiration) GetAccountIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *Expiration) SetAccountId(v float32) {
	o.AccountId = v
}

// GetCompanyId returns the CompanyId field value
func (o *Expiration) GetCompanyId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *Expiration) GetCompanyIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *Expiration) SetCompanyId(v float32) {
	o.CompanyId = v
}

// GetAssetLayoutFieldId returns the AssetLayoutFieldId field value if set, zero value otherwise.
func (o *Expiration) GetAssetLayoutFieldId() float32 {
	if o == nil || IsNil(o.AssetLayoutFieldId) {
		var ret float32
		return ret
	}
	return *o.AssetLayoutFieldId
}

// GetAssetLayoutFieldIdOk returns a tuple with the AssetLayoutFieldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Expiration) GetAssetLayoutFieldIdOk() (*float32, bool) {
	if o == nil || IsNil(o.AssetLayoutFieldId) {
		return nil, false
	}
	return o.AssetLayoutFieldId, true
}

// HasAssetLayoutFieldId returns a boolean if a field has been set.
func (o *Expiration) HasAssetLayoutFieldId() bool {
	if o != nil && !IsNil(o.AssetLayoutFieldId) {
		return true
	}

	return false
}

// SetAssetLayoutFieldId gets a reference to the given float32 and assigns it to the AssetLayoutFieldId field.
func (o *Expiration) SetAssetLayoutFieldId(v float32) {
	o.AssetLayoutFieldId = &v
}

// GetSyncId returns the SyncId field value if set, zero value otherwise.
func (o *Expiration) GetSyncId() float32 {
	if o == nil || IsNil(o.SyncId) {
		var ret float32
		return ret
	}
	return *o.SyncId
}

// GetSyncIdOk returns a tuple with the SyncId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Expiration) GetSyncIdOk() (*float32, bool) {
	if o == nil || IsNil(o.SyncId) {
		return nil, false
	}
	return o.SyncId, true
}

// HasSyncId returns a boolean if a field has been set.
func (o *Expiration) HasSyncId() bool {
	if o != nil && !IsNil(o.SyncId) {
		return true
	}

	return false
}

// SetSyncId gets a reference to the given float32 and assigns it to the SyncId field.
func (o *Expiration) SetSyncId(v float32) {
	o.SyncId = &v
}

// GetDiscardedAt returns the DiscardedAt field value if set, zero value otherwise.
func (o *Expiration) GetDiscardedAt() time.Time {
	if o == nil || IsNil(o.DiscardedAt) {
		var ret time.Time
		return ret
	}
	return *o.DiscardedAt
}

// GetDiscardedAtOk returns a tuple with the DiscardedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Expiration) GetDiscardedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DiscardedAt) {
		return nil, false
	}
	return o.DiscardedAt, true
}

// HasDiscardedAt returns a boolean if a field has been set.
func (o *Expiration) HasDiscardedAt() bool {
	if o != nil && !IsNil(o.DiscardedAt) {
		return true
	}

	return false
}

// SetDiscardedAt gets a reference to the given time.Time and assigns it to the DiscardedAt field.
func (o *Expiration) SetDiscardedAt(v time.Time) {
	o.DiscardedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Expiration) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Expiration) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Expiration) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Expiration) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Expiration) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Expiration) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Expiration) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Expiration) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetExpirationType returns the ExpirationType field value
func (o *Expiration) GetExpirationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpirationType
}

// GetExpirationTypeOk returns a tuple with the ExpirationType field value
// and a boolean to check if the value has been set.
func (o *Expiration) GetExpirationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpirationType, true
}

// SetExpirationType sets field value
func (o *Expiration) SetExpirationType(v string) {
	o.ExpirationType = v
}

// GetAssetFieldId returns the AssetFieldId field value if set, zero value otherwise.
func (o *Expiration) GetAssetFieldId() float32 {
	if o == nil || IsNil(o.AssetFieldId) {
		var ret float32
		return ret
	}
	return *o.AssetFieldId
}

// GetAssetFieldIdOk returns a tuple with the AssetFieldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Expiration) GetAssetFieldIdOk() (*float32, bool) {
	if o == nil || IsNil(o.AssetFieldId) {
		return nil, false
	}
	return o.AssetFieldId, true
}

// HasAssetFieldId returns a boolean if a field has been set.
func (o *Expiration) HasAssetFieldId() bool {
	if o != nil && !IsNil(o.AssetFieldId) {
		return true
	}

	return false
}

// SetAssetFieldId gets a reference to the given float32 and assigns it to the AssetFieldId field.
func (o *Expiration) SetAssetFieldId(v float32) {
	o.AssetFieldId = &v
}

func (o Expiration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Expiration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["date"] = o.Date
	toSerialize["expirationable_type"] = o.ExpirationableType
	toSerialize["expirationable_id"] = o.ExpirationableId
	toSerialize["account_id"] = o.AccountId
	toSerialize["company_id"] = o.CompanyId
	if !IsNil(o.AssetLayoutFieldId) {
		toSerialize["asset_layout_field_id"] = o.AssetLayoutFieldId
	}
	if !IsNil(o.SyncId) {
		toSerialize["sync_id"] = o.SyncId
	}
	if !IsNil(o.DiscardedAt) {
		toSerialize["discarded_at"] = o.DiscardedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["expiration_type"] = o.ExpirationType
	if !IsNil(o.AssetFieldId) {
		toSerialize["asset_field_id"] = o.AssetFieldId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Expiration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"date",
		"expirationable_type",
		"expirationable_id",
		"account_id",
		"company_id",
		"expiration_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpiration := _Expiration{}

	err = json.Unmarshal(data, &varExpiration)

	if err != nil {
		return err
	}

	*o = Expiration(varExpiration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "date")
		delete(additionalProperties, "expirationable_type")
		delete(additionalProperties, "expirationable_id")
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "company_id")
		delete(additionalProperties, "asset_layout_field_id")
		delete(additionalProperties, "sync_id")
		delete(additionalProperties, "discarded_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "expiration_type")
		delete(additionalProperties, "asset_field_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExpiration struct {
	value *Expiration
	isSet bool
}

func (v NullableExpiration) Get() *Expiration {
	return v.value
}

func (v *NullableExpiration) Set(val *Expiration) {
	v.value = val
	v.isSet = true
}

func (v NullableExpiration) IsSet() bool {
	return v.isSet
}

func (v *NullableExpiration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpiration(val *Expiration) *NullableExpiration {
	return &NullableExpiration{value: val, isSet: true}
}

func (v NullableExpiration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpiration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
