/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the UpdateProcedureRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProcedureRequest{}

// UpdateProcedureRequest struct for UpdateProcedureRequest
type UpdateProcedureRequest struct {
	// The new name for the procedure.
	Name *string `json:"name,omitempty"`
	// The new description for the procedure.
	Description *string `json:"description,omitempty"`
	// When true, sets both template and remove_completion_ability to true. When false, sets both to false.
	CompanyTemplate *bool `json:"company_template,omitempty"`
	// The ID of the company this procedure should be transferred to. Set to null to make this a global template.
	CompanyId *int64 `json:"company_id,omitempty"`
	// When true, archives the procedure by setting discarded_at. When false, unarchives the procedure by clearing discarded_at.
	Archived             *bool `json:"archived,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateProcedureRequest UpdateProcedureRequest

// NewUpdateProcedureRequest instantiates a new UpdateProcedureRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProcedureRequest() *UpdateProcedureRequest {
	this := UpdateProcedureRequest{}
	return &this
}

// NewUpdateProcedureRequestWithDefaults instantiates a new UpdateProcedureRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProcedureRequestWithDefaults() *UpdateProcedureRequest {
	this := UpdateProcedureRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateProcedureRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateProcedureRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateProcedureRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateProcedureRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateProcedureRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateProcedureRequest) SetDescription(v string) {
	o.Description = &v
}

// GetCompanyTemplate returns the CompanyTemplate field value if set, zero value otherwise.
func (o *UpdateProcedureRequest) GetCompanyTemplate() bool {
	if o == nil || IsNil(o.CompanyTemplate) {
		var ret bool
		return ret
	}
	return *o.CompanyTemplate
}

// GetCompanyTemplateOk returns a tuple with the CompanyTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureRequest) GetCompanyTemplateOk() (*bool, bool) {
	if o == nil || IsNil(o.CompanyTemplate) {
		return nil, false
	}
	return o.CompanyTemplate, true
}

// HasCompanyTemplate returns a boolean if a field has been set.
func (o *UpdateProcedureRequest) HasCompanyTemplate() bool {
	if o != nil && !IsNil(o.CompanyTemplate) {
		return true
	}

	return false
}

// SetCompanyTemplate gets a reference to the given bool and assigns it to the CompanyTemplate field.
func (o *UpdateProcedureRequest) SetCompanyTemplate(v bool) {
	o.CompanyTemplate = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *UpdateProcedureRequest) GetCompanyId() int64 {
	if o == nil || IsNil(o.CompanyId) {
		var ret int64
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureRequest) GetCompanyIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *UpdateProcedureRequest) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int64 and assigns it to the CompanyId field.
func (o *UpdateProcedureRequest) SetCompanyId(v int64) {
	o.CompanyId = &v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *UpdateProcedureRequest) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProcedureRequest) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *UpdateProcedureRequest) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *UpdateProcedureRequest) SetArchived(v bool) {
	o.Archived = &v
}

func (o UpdateProcedureRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProcedureRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CompanyTemplate) {
		toSerialize["company_template"] = o.CompanyTemplate
	}
	if !IsNil(o.CompanyId) {
		toSerialize["company_id"] = o.CompanyId
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateProcedureRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateProcedureRequest := _UpdateProcedureRequest{}

	err = json.Unmarshal(data, &varUpdateProcedureRequest)

	if err != nil {
		return err
	}

	*o = UpdateProcedureRequest(varUpdateProcedureRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "company_template")
		delete(additionalProperties, "company_id")
		delete(additionalProperties, "archived")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateProcedureRequest struct {
	value *UpdateProcedureRequest
	isSet bool
}

func (v NullableUpdateProcedureRequest) Get() *UpdateProcedureRequest {
	return v.value
}

func (v *NullableUpdateProcedureRequest) Set(val *UpdateProcedureRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProcedureRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProcedureRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProcedureRequest(val *UpdateProcedureRequest) *NullableUpdateProcedureRequest {
	return &NullableUpdateProcedureRequest{value: val, isSet: true}
}

func (v NullableUpdateProcedureRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProcedureRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
