/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the PostExportsRequestExport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostExportsRequestExport{}

// PostExportsRequestExport struct for PostExportsRequestExport
type PostExportsRequestExport struct {
	// True or False to indicate if websites should be included in the export
	IncludeWebsites *bool `json:"include_websites,omitempty"`
	// True or False to indicate if passwords should be included in the export
	IncludePasswords *bool `json:"include_passwords,omitempty"`
	// Specify the company to export
	CompanyId *int64 `json:"company_id,omitempty"`
	// Specify the export format: pdf, csv, or s3
	Format *string `json:"format,omitempty"`
	// Array of asset layout IDs to include in the export
	AssetLayoutIds       []int64 `json:"asset_layout_ids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PostExportsRequestExport PostExportsRequestExport

// NewPostExportsRequestExport instantiates a new PostExportsRequestExport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostExportsRequestExport() *PostExportsRequestExport {
	this := PostExportsRequestExport{}
	return &this
}

// NewPostExportsRequestExportWithDefaults instantiates a new PostExportsRequestExport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostExportsRequestExportWithDefaults() *PostExportsRequestExport {
	this := PostExportsRequestExport{}
	return &this
}

// GetIncludeWebsites returns the IncludeWebsites field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetIncludeWebsites() bool {
	if o == nil || IsNil(o.IncludeWebsites) {
		var ret bool
		return ret
	}
	return *o.IncludeWebsites
}

// GetIncludeWebsitesOk returns a tuple with the IncludeWebsites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludeWebsitesOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeWebsites) {
		return nil, false
	}
	return o.IncludeWebsites, true
}

// HasIncludeWebsites returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasIncludeWebsites() bool {
	if o != nil && !IsNil(o.IncludeWebsites) {
		return true
	}

	return false
}

// SetIncludeWebsites gets a reference to the given bool and assigns it to the IncludeWebsites field.
func (o *PostExportsRequestExport) SetIncludeWebsites(v bool) {
	o.IncludeWebsites = &v
}

// GetIncludePasswords returns the IncludePasswords field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetIncludePasswords() bool {
	if o == nil || IsNil(o.IncludePasswords) {
		var ret bool
		return ret
	}
	return *o.IncludePasswords
}

// GetIncludePasswordsOk returns a tuple with the IncludePasswords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetIncludePasswordsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludePasswords) {
		return nil, false
	}
	return o.IncludePasswords, true
}

// HasIncludePasswords returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasIncludePasswords() bool {
	if o != nil && !IsNil(o.IncludePasswords) {
		return true
	}

	return false
}

// SetIncludePasswords gets a reference to the given bool and assigns it to the IncludePasswords field.
func (o *PostExportsRequestExport) SetIncludePasswords(v bool) {
	o.IncludePasswords = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetCompanyId() int64 {
	if o == nil || IsNil(o.CompanyId) {
		var ret int64
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetCompanyIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int64 and assigns it to the CompanyId field.
func (o *PostExportsRequestExport) SetCompanyId(v int64) {
	o.CompanyId = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *PostExportsRequestExport) SetFormat(v string) {
	o.Format = &v
}

// GetAssetLayoutIds returns the AssetLayoutIds field value if set, zero value otherwise.
func (o *PostExportsRequestExport) GetAssetLayoutIds() []int64 {
	if o == nil || IsNil(o.AssetLayoutIds) {
		var ret []int64
		return ret
	}
	return o.AssetLayoutIds
}

// GetAssetLayoutIdsOk returns a tuple with the AssetLayoutIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExportsRequestExport) GetAssetLayoutIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.AssetLayoutIds) {
		return nil, false
	}
	return o.AssetLayoutIds, true
}

// HasAssetLayoutIds returns a boolean if a field has been set.
func (o *PostExportsRequestExport) HasAssetLayoutIds() bool {
	if o != nil && !IsNil(o.AssetLayoutIds) {
		return true
	}

	return false
}

// SetAssetLayoutIds gets a reference to the given []int64 and assigns it to the AssetLayoutIds field.
func (o *PostExportsRequestExport) SetAssetLayoutIds(v []int64) {
	o.AssetLayoutIds = v
}

func (o PostExportsRequestExport) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostExportsRequestExport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IncludeWebsites) {
		toSerialize["include_websites"] = o.IncludeWebsites
	}
	if !IsNil(o.IncludePasswords) {
		toSerialize["include_passwords"] = o.IncludePasswords
	}
	if !IsNil(o.CompanyId) {
		toSerialize["company_id"] = o.CompanyId
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.AssetLayoutIds) {
		toSerialize["asset_layout_ids"] = o.AssetLayoutIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PostExportsRequestExport) UnmarshalJSON(data []byte) (err error) {
	varPostExportsRequestExport := _PostExportsRequestExport{}

	err = json.Unmarshal(data, &varPostExportsRequestExport)

	if err != nil {
		return err
	}

	*o = PostExportsRequestExport(varPostExportsRequestExport)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "include_websites")
		delete(additionalProperties, "include_passwords")
		delete(additionalProperties, "company_id")
		delete(additionalProperties, "format")
		delete(additionalProperties, "asset_layout_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePostExportsRequestExport struct {
	value *PostExportsRequestExport
	isSet bool
}

func (v NullablePostExportsRequestExport) Get() *PostExportsRequestExport {
	return v.value
}

func (v *NullablePostExportsRequestExport) Set(val *PostExportsRequestExport) {
	v.value = val
	v.isSet = true
}

func (v NullablePostExportsRequestExport) IsSet() bool {
	return v.isSet
}

func (v *NullablePostExportsRequestExport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostExportsRequestExport(val *PostExportsRequestExport) *NullablePostExportsRequestExport {
	return &NullablePostExportsRequestExport{value: val, isSet: true}
}

func (v NullablePostExportsRequestExport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostExportsRequestExport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
