/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateListRequestList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateListRequestList{}

// CreateListRequestList struct for CreateListRequestList
type CreateListRequestList struct {
	// Name of the list
	Name string `json:"name"`
	// Array of list items to create
	ListItemsAttributes  []CreateListRequestListListItemsAttributesInner `json:"list_items_attributes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateListRequestList CreateListRequestList

// NewCreateListRequestList instantiates a new CreateListRequestList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateListRequestList(name string) *CreateListRequestList {
	this := CreateListRequestList{}
	this.Name = name
	return &this
}

// NewCreateListRequestListWithDefaults instantiates a new CreateListRequestList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateListRequestListWithDefaults() *CreateListRequestList {
	this := CreateListRequestList{}
	return &this
}

// GetName returns the Name field value
func (o *CreateListRequestList) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateListRequestList) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateListRequestList) SetName(v string) {
	o.Name = v
}

// GetListItemsAttributes returns the ListItemsAttributes field value if set, zero value otherwise.
func (o *CreateListRequestList) GetListItemsAttributes() []CreateListRequestListListItemsAttributesInner {
	if o == nil || IsNil(o.ListItemsAttributes) {
		var ret []CreateListRequestListListItemsAttributesInner
		return ret
	}
	return o.ListItemsAttributes
}

// GetListItemsAttributesOk returns a tuple with the ListItemsAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateListRequestList) GetListItemsAttributesOk() ([]CreateListRequestListListItemsAttributesInner, bool) {
	if o == nil || IsNil(o.ListItemsAttributes) {
		return nil, false
	}
	return o.ListItemsAttributes, true
}

// HasListItemsAttributes returns a boolean if a field has been set.
func (o *CreateListRequestList) HasListItemsAttributes() bool {
	if o != nil && !IsNil(o.ListItemsAttributes) {
		return true
	}

	return false
}

// SetListItemsAttributes gets a reference to the given []CreateListRequestListListItemsAttributesInner and assigns it to the ListItemsAttributes field.
func (o *CreateListRequestList) SetListItemsAttributes(v []CreateListRequestListListItemsAttributesInner) {
	o.ListItemsAttributes = v
}

func (o CreateListRequestList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateListRequestList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.ListItemsAttributes) {
		toSerialize["list_items_attributes"] = o.ListItemsAttributes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateListRequestList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateListRequestList := _CreateListRequestList{}

	err = json.Unmarshal(data, &varCreateListRequestList)

	if err != nil {
		return err
	}

	*o = CreateListRequestList(varCreateListRequestList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "list_items_attributes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateListRequestList struct {
	value *CreateListRequestList
	isSet bool
}

func (v NullableCreateListRequestList) Get() *CreateListRequestList {
	return v.value
}

func (v *NullableCreateListRequestList) Set(val *CreateListRequestList) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateListRequestList) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateListRequestList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateListRequestList(val *CreateListRequestList) *NullableCreateListRequestList {
	return &NullableCreateListRequestList{value: val, isSet: true}
}

func (v NullableCreateListRequestList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateListRequestList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
