/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateFlagRequestFlag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFlagRequestFlag{}

// CreateFlagRequestFlag struct for CreateFlagRequestFlag
type CreateFlagRequestFlag struct {
	// ID of the flag type
	FlagTypeId int32 `json:"flag_type_id"`
	// Optional description for the flag
	Description *string `json:"description,omitempty"`
	// The type of record being flagged
	FlagableType string `json:"flagable_type"`
	// The ID of the record being flagged
	FlagableId           int32 `json:"flagable_id"`
	AdditionalProperties map[string]interface{}
}

type _CreateFlagRequestFlag CreateFlagRequestFlag

// NewCreateFlagRequestFlag instantiates a new CreateFlagRequestFlag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFlagRequestFlag(flagTypeId int32, flagableType string, flagableId int32) *CreateFlagRequestFlag {
	this := CreateFlagRequestFlag{}
	this.FlagTypeId = flagTypeId
	this.FlagableType = flagableType
	this.FlagableId = flagableId
	return &this
}

// NewCreateFlagRequestFlagWithDefaults instantiates a new CreateFlagRequestFlag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFlagRequestFlagWithDefaults() *CreateFlagRequestFlag {
	this := CreateFlagRequestFlag{}
	return &this
}

// GetFlagTypeId returns the FlagTypeId field value
func (o *CreateFlagRequestFlag) GetFlagTypeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FlagTypeId
}

// GetFlagTypeIdOk returns a tuple with the FlagTypeId field value
// and a boolean to check if the value has been set.
func (o *CreateFlagRequestFlag) GetFlagTypeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlagTypeId, true
}

// SetFlagTypeId sets field value
func (o *CreateFlagRequestFlag) SetFlagTypeId(v int32) {
	o.FlagTypeId = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateFlagRequestFlag) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFlagRequestFlag) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateFlagRequestFlag) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateFlagRequestFlag) SetDescription(v string) {
	o.Description = &v
}

// GetFlagableType returns the FlagableType field value
func (o *CreateFlagRequestFlag) GetFlagableType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FlagableType
}

// GetFlagableTypeOk returns a tuple with the FlagableType field value
// and a boolean to check if the value has been set.
func (o *CreateFlagRequestFlag) GetFlagableTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlagableType, true
}

// SetFlagableType sets field value
func (o *CreateFlagRequestFlag) SetFlagableType(v string) {
	o.FlagableType = v
}

// GetFlagableId returns the FlagableId field value
func (o *CreateFlagRequestFlag) GetFlagableId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FlagableId
}

// GetFlagableIdOk returns a tuple with the FlagableId field value
// and a boolean to check if the value has been set.
func (o *CreateFlagRequestFlag) GetFlagableIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlagableId, true
}

// SetFlagableId sets field value
func (o *CreateFlagRequestFlag) SetFlagableId(v int32) {
	o.FlagableId = v
}

func (o CreateFlagRequestFlag) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFlagRequestFlag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["flag_type_id"] = o.FlagTypeId
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["flagable_type"] = o.FlagableType
	toSerialize["flagable_id"] = o.FlagableId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateFlagRequestFlag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"flag_type_id",
		"flagable_type",
		"flagable_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateFlagRequestFlag := _CreateFlagRequestFlag{}

	err = json.Unmarshal(data, &varCreateFlagRequestFlag)

	if err != nil {
		return err
	}

	*o = CreateFlagRequestFlag(varCreateFlagRequestFlag)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "flag_type_id")
		delete(additionalProperties, "description")
		delete(additionalProperties, "flagable_type")
		delete(additionalProperties, "flagable_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateFlagRequestFlag struct {
	value *CreateFlagRequestFlag
	isSet bool
}

func (v NullableCreateFlagRequestFlag) Get() *CreateFlagRequestFlag {
	return v.value
}

func (v *NullableCreateFlagRequestFlag) Set(val *CreateFlagRequestFlag) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFlagRequestFlag) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFlagRequestFlag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFlagRequestFlag(val *CreateFlagRequestFlag) *NullableCreateFlagRequestFlag {
	return &NullableCreateFlagRequestFlag{value: val, isSet: true}
}

func (v NullableCreateFlagRequestFlag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFlagRequestFlag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
