/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the GetCompaniesId200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCompaniesId200Response{}

// GetCompaniesId200Response struct for GetCompaniesId200Response
type GetCompaniesId200Response struct {
	Company              *Company `json:"company,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetCompaniesId200Response GetCompaniesId200Response

// NewGetCompaniesId200Response instantiates a new GetCompaniesId200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCompaniesId200Response() *GetCompaniesId200Response {
	this := GetCompaniesId200Response{}
	return &this
}

// NewGetCompaniesId200ResponseWithDefaults instantiates a new GetCompaniesId200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCompaniesId200ResponseWithDefaults() *GetCompaniesId200Response {
	this := GetCompaniesId200Response{}
	return &this
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *GetCompaniesId200Response) GetCompany() Company {
	if o == nil || IsNil(o.Company) {
		var ret Company
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCompaniesId200Response) GetCompanyOk() (*Company, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *GetCompaniesId200Response) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given Company and assigns it to the Company field.
func (o *GetCompaniesId200Response) SetCompany(v Company) {
	o.Company = &v
}

func (o GetCompaniesId200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCompaniesId200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCompaniesId200Response) UnmarshalJSON(data []byte) (err error) {
	varGetCompaniesId200Response := _GetCompaniesId200Response{}

	err = json.Unmarshal(data, &varGetCompaniesId200Response)

	if err != nil {
		return err
	}

	*o = GetCompaniesId200Response(varGetCompaniesId200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "company")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCompaniesId200Response struct {
	value *GetCompaniesId200Response
	isSet bool
}

func (v NullableGetCompaniesId200Response) Get() *GetCompaniesId200Response {
	return v.value
}

func (v *NullableGetCompaniesId200Response) Set(val *GetCompaniesId200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCompaniesId200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCompaniesId200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCompaniesId200Response(val *GetCompaniesId200Response) *NullableGetCompaniesId200Response {
	return &NullableGetCompaniesId200Response{value: val, isSet: true}
}

func (v NullableGetCompaniesId200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCompaniesId200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
