/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the IpAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpAddress{}

// IpAddress struct for IpAddress
type IpAddress struct {
	// The IP address.
	Address *string `json:"address,omitempty"`
	// The status of the IP address. Must be one of: unassigned, assigned, reserved, deprecated, dhcp, or slaac
	Status *string `json:"status,omitempty"`
	// The Fully Qualified Domain Name associated with the IP address.
	Fqdn *string `json:"fqdn,omitempty"`
	// A brief description of the IP address.
	Description *string `json:"description,omitempty"`
	// Additional comments about the IP address.
	Notes *string `json:"notes,omitempty"`
	// The identifier of the asset associated with this IP address.
	AssetId *int64 `json:"asset_id,omitempty"`
	// The identifier of the network to which this IP address belongs.
	NetworkId *int64 `json:"network_id,omitempty"`
	// The identifier of the company that owns this IP address.
	CompanyId *int64 `json:"company_id,omitempty"`
	// If true, the server will **not** attempt to verify that the FQDN resolves to the address when the record is created or updated. Use for internal-only hostnames.
	SkipDnsValidation    *bool `json:"skip_dns_validation,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IpAddress IpAddress

// NewIpAddress instantiates a new IpAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpAddress() *IpAddress {
	this := IpAddress{}
	return &this
}

// NewIpAddressWithDefaults instantiates a new IpAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpAddressWithDefaults() *IpAddress {
	this := IpAddress{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *IpAddress) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *IpAddress) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *IpAddress) SetAddress(v string) {
	o.Address = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *IpAddress) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *IpAddress) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *IpAddress) SetStatus(v string) {
	o.Status = &v
}

// GetFqdn returns the Fqdn field value if set, zero value otherwise.
func (o *IpAddress) GetFqdn() string {
	if o == nil || IsNil(o.Fqdn) {
		var ret string
		return ret
	}
	return *o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetFqdnOk() (*string, bool) {
	if o == nil || IsNil(o.Fqdn) {
		return nil, false
	}
	return o.Fqdn, true
}

// HasFqdn returns a boolean if a field has been set.
func (o *IpAddress) HasFqdn() bool {
	if o != nil && !IsNil(o.Fqdn) {
		return true
	}

	return false
}

// SetFqdn gets a reference to the given string and assigns it to the Fqdn field.
func (o *IpAddress) SetFqdn(v string) {
	o.Fqdn = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IpAddress) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IpAddress) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IpAddress) SetDescription(v string) {
	o.Description = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *IpAddress) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *IpAddress) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *IpAddress) SetNotes(v string) {
	o.Notes = &v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *IpAddress) GetAssetId() int64 {
	if o == nil || IsNil(o.AssetId) {
		var ret int64
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetAssetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *IpAddress) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given int64 and assigns it to the AssetId field.
func (o *IpAddress) SetAssetId(v int64) {
	o.AssetId = &v
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise.
func (o *IpAddress) GetNetworkId() int64 {
	if o == nil || IsNil(o.NetworkId) {
		var ret int64
		return ret
	}
	return *o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetNetworkIdOk() (*int64, bool) {
	if o == nil || IsNil(o.NetworkId) {
		return nil, false
	}
	return o.NetworkId, true
}

// HasNetworkId returns a boolean if a field has been set.
func (o *IpAddress) HasNetworkId() bool {
	if o != nil && !IsNil(o.NetworkId) {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given int64 and assigns it to the NetworkId field.
func (o *IpAddress) SetNetworkId(v int64) {
	o.NetworkId = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *IpAddress) GetCompanyId() int64 {
	if o == nil || IsNil(o.CompanyId) {
		var ret int64
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetCompanyIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *IpAddress) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int64 and assigns it to the CompanyId field.
func (o *IpAddress) SetCompanyId(v int64) {
	o.CompanyId = &v
}

// GetSkipDnsValidation returns the SkipDnsValidation field value if set, zero value otherwise.
func (o *IpAddress) GetSkipDnsValidation() bool {
	if o == nil || IsNil(o.SkipDnsValidation) {
		var ret bool
		return ret
	}
	return *o.SkipDnsValidation
}

// GetSkipDnsValidationOk returns a tuple with the SkipDnsValidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpAddress) GetSkipDnsValidationOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipDnsValidation) {
		return nil, false
	}
	return o.SkipDnsValidation, true
}

// HasSkipDnsValidation returns a boolean if a field has been set.
func (o *IpAddress) HasSkipDnsValidation() bool {
	if o != nil && !IsNil(o.SkipDnsValidation) {
		return true
	}

	return false
}

// SetSkipDnsValidation gets a reference to the given bool and assigns it to the SkipDnsValidation field.
func (o *IpAddress) SetSkipDnsValidation(v bool) {
	o.SkipDnsValidation = &v
}

func (o IpAddress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Fqdn) {
		toSerialize["fqdn"] = o.Fqdn
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.AssetId) {
		toSerialize["asset_id"] = o.AssetId
	}
	if !IsNil(o.NetworkId) {
		toSerialize["network_id"] = o.NetworkId
	}
	if !IsNil(o.CompanyId) {
		toSerialize["company_id"] = o.CompanyId
	}
	if !IsNil(o.SkipDnsValidation) {
		toSerialize["skip_dns_validation"] = o.SkipDnsValidation
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IpAddress) UnmarshalJSON(data []byte) (err error) {
	varIpAddress := _IpAddress{}

	err = json.Unmarshal(data, &varIpAddress)

	if err != nil {
		return err
	}

	*o = IpAddress(varIpAddress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "status")
		delete(additionalProperties, "fqdn")
		delete(additionalProperties, "description")
		delete(additionalProperties, "notes")
		delete(additionalProperties, "asset_id")
		delete(additionalProperties, "network_id")
		delete(additionalProperties, "company_id")
		delete(additionalProperties, "skip_dns_validation")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIpAddress struct {
	value *IpAddress
	isSet bool
}

func (v NullableIpAddress) Get() *IpAddress {
	return v.value
}

func (v *NullableIpAddress) Set(val *IpAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableIpAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableIpAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpAddress(val *IpAddress) *NullableIpAddress {
	return &NullableIpAddress{value: val, isSet: true}
}

func (v NullableIpAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
