/*
Hudu API Documentation

<h1>Welcome to the Hudu REST API</h1> <p>The Hudu REST API enables seamless automation of your IT documentation. It's organized into various resources, each with its own specific endpoint.</p>  <h2>Authentication</h2> <p>All API requests require authentication using an API key. To obtain a key, go to <strong>Hudu Admin → Basic Information → API Keys</strong>.</p> <p>Include your API key in the request header, like so:</p> <pre><code>curl https://[YOUR_DOMAIN]/api/v1/companies?page=1 \\   -H \"x-api-key: YOUR_API_KEY_HERE\"</code></pre> <p>You can create and delete API keys at any time.</p>  <h2>Scoping API Keys</h2> <p>When creating an API key, you can configure the following permissions:</p> <ul>   <li>Access to passwords (all REST actions)</li>   <li>Destructive actions (DELETE)</li>   <li>Export capabilities</li>   <li>Whitelisted IPs</li>   <li>Company-specific access</li> </ul> <p>We recommend only granting the minimum required access for each application.</p>  <h2>Format</h2> <p>All API requests must use <strong>JSON</strong> format unless otherwise specified.</p>  <h2>Terminology</h2> <p>Some names in the API differ from those in the Hudu UI:</p> <table>   <thead>     <tr>       <th>Name in Hudu</th>       <th>Name in API</th>     </tr>   </thead>   <tbody>     <tr>       <td>Company (customizable)</td>       <td>Company</td>     </tr>     <tr>       <td>Password</td>       <td>AssetPassword</td>     </tr>     <tr>       <td>Knowledge Base Article</td>       <td>Article</td>     </tr>     <tr>       <td>Process</td>       <td>Procedure</td>     </tr>   </tbody> </table>  <h2>Pagination</h2> <p>All responses are paginated with 25 results per page. Use the <code>?page=X</code> query parameter to navigate.</p>  <h2>Rate Limiting</h2> <p>The API supports up to <strong>300 requests per minute</strong>.</p>  <p>&copy; 2023 Hudu Technologies, Inc. All rights reserved.</p>

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package huduapi

import (
	"encoding/json"
)

// checks if the GetMatchers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMatchers200Response{}

// GetMatchers200Response struct for GetMatchers200Response
type GetMatchers200Response struct {
	Matchers             []Matcher `json:"matchers,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetMatchers200Response GetMatchers200Response

// NewGetMatchers200Response instantiates a new GetMatchers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMatchers200Response() *GetMatchers200Response {
	this := GetMatchers200Response{}
	return &this
}

// NewGetMatchers200ResponseWithDefaults instantiates a new GetMatchers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMatchers200ResponseWithDefaults() *GetMatchers200Response {
	this := GetMatchers200Response{}
	return &this
}

// GetMatchers returns the Matchers field value if set, zero value otherwise.
func (o *GetMatchers200Response) GetMatchers() []Matcher {
	if o == nil || IsNil(o.Matchers) {
		var ret []Matcher
		return ret
	}
	return o.Matchers
}

// GetMatchersOk returns a tuple with the Matchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMatchers200Response) GetMatchersOk() ([]Matcher, bool) {
	if o == nil || IsNil(o.Matchers) {
		return nil, false
	}
	return o.Matchers, true
}

// HasMatchers returns a boolean if a field has been set.
func (o *GetMatchers200Response) HasMatchers() bool {
	if o != nil && !IsNil(o.Matchers) {
		return true
	}

	return false
}

// SetMatchers gets a reference to the given []Matcher and assigns it to the Matchers field.
func (o *GetMatchers200Response) SetMatchers(v []Matcher) {
	o.Matchers = v
}

func (o GetMatchers200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMatchers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Matchers) {
		toSerialize["matchers"] = o.Matchers
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetMatchers200Response) UnmarshalJSON(data []byte) (err error) {
	varGetMatchers200Response := _GetMatchers200Response{}

	err = json.Unmarshal(data, &varGetMatchers200Response)

	if err != nil {
		return err
	}

	*o = GetMatchers200Response(varGetMatchers200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "matchers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetMatchers200Response struct {
	value *GetMatchers200Response
	isSet bool
}

func (v NullableGetMatchers200Response) Get() *GetMatchers200Response {
	return v.value
}

func (v *NullableGetMatchers200Response) Set(val *GetMatchers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMatchers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMatchers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMatchers200Response(val *GetMatchers200Response) *NullableGetMatchers200Response {
	return &NullableGetMatchers200Response{value: val, isSet: true}
}

func (v NullableGetMatchers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMatchers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
